version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/task-app
      - PORT=4000
    volumes:
      - ./src:/home/node/app/src
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
  mongo:
    image: mongo
    restart: always
    ports:
      - 27000:27017
    volumes:
      - db_data:/data/db

volumes:
  db_data: